name: CI

on:
  push:
    branches: [ main, Aysel ]
  pull_request:
    branches: [ main ]

jobs:
  static-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run static checks for all services
        run: |
          chmod +x ./run-static-checks.sh
          ./run-static-checks.sh

      - name: Archive test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: result/tests/test-report.txt

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            worker/bin/
            result/dist/
            vote/build/
